create table if not exists users (
    id serial primary key,
    username varchar(50) not null unique,
    password varchar(255) not null,
    email varchar(100) not null unique,
    created_at timestamp default current_timestamp
);

create table if not exists history_games (
    id serial primary key,
    player1_id int references users(id),
    player2_id int references users(id),
    winner_id int references users(id),
    result varchar(20) not null,
    ended_by varchar(20) not null,
    created_at timestamp default current_timestamp
);

create table if not exists moves (
    id serial primary key,
    game_id int references history_games(id),
    player_id int references users(id),
    move varchar(10) not null,
    created_at timestamp default current_timestamp
);

CREATE TABLE IF NOT EXISTS game (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  -- id de la personne qui à créé la partie
  creator_id INTEGER REFERENCES users(id),
  -- id de la personne qui join, null par défaut mais s'update lorsque qqun join
  joiner_id INTEGER REFERENCES users(id) DEFAULT null,
  -- Le code à six chiffres affiché par le créateur de la partie.
  code TEXT NOT NULL UNIQUE,
  -- 'lobby' | 'en cours' | 'finished'
  state TEXT NOT NULL DEFAULT 'lobby'
);