create table if not exists users (
    id serial primary key,
    username varchar(50) not null unique,
    password varchar(255) not null,
    email varchar(100) not null unique,
    created_at timestamp default current_timestamp
);

CREATE TABLE IF NOT EXISTS game (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  -- id de la personne qui à créé la partie
  creator_id INTEGER REFERENCES users(id),
  -- id de la personne qui join, null par défaut mais s'update lorsque qqun join
  joiner_id INTEGER REFERENCES users(id) DEFAULT null,
  -- Le code à six chiffres affiché par le créateur de la partie.
  code TEXT NOT NULL UNIQUE,
  -- 'lobby' | 'en cours' | 'finished'
  state TEXT NOT NULL DEFAULT 'lobby'
);

CREATE TABLE IF NOT EXISTS game_details (
  id          SERIAL PRIMARY KEY,
  game_id     INTEGER NOT NULL UNIQUE REFERENCES game(id) ON DELETE CASCADE,
  -- historique des coups joués sur la partie, (1. e4 e5 2. Nf3 Nc6 ...)
  pgn         TEXT NOT NULL DEFAULT '',
  -- snapshot de l'échiquier en FEN notation
  fen         TEXT NOT NULL DEFAULT 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  move_count  INTEGER NOT NULL DEFAULT 0,
  result      TEXT CHECK (result IN ('white', 'black', 'draw')),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);